---
- name: "Decomissioning VMs"
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - config/common.yml
    - config/secrets.yml
    - inventory.yml

  tasks:
    - name: "MAIN | List of VMs to be **[[DELETED]]**. You better be sure about this:"
      debug: var=inventory_item.vm_name
      with_items: "{{ inventory }}"
      loop_control:
        loop_var: inventory_item

    - pause:
        seconds: 30
      
    - name: "MAIN | UnInstalling base packages on VMs"
      include_role:
        name: base_packages
      vars:
        # Common Parameters #
        vm_ip: "{{ inventory_item.vm_ip }}"
        vm_dns_domain: "{{ inventory_item.vm_dns_domain | default(default_vm_dns_domain) }}"
        
        vm_name: "{{ inventory_item.vm_name }}"
        vm_template: "{{ inventory_item.vm_template }}"
        
        datacenter: "{{ inventory_item.datacenter | default(default_datacenter) }}"
        cluster: "{{ inventory_item.cluster | default(default_cluster) }}"
        resource_pool: "{{ inventory_item.resource_pool | default(default_resource_pool) }}"

        ad_ou: "{{ inventory_item.ad_ou | default(default_ad_ou) }}"
        local_admin_groups: "{{ inventory_item.local_admin_groups | default(default_local_admin_groups) }}"
        # End Parameters #
        
        os: "{{ inventory_item.os }}"
        ansible_connection: winrm
        ansible_user: "{{ vm_win_username }}"
        ansible_password: "{{ vm_win_password }}"
        ansible_winrm_server_cert_validation: ignore
        uninstall: true
      with_items:
        - "{{ inventory }}"
      loop_control:
        loop_var: inventory_item
      when: inventory_item.os == "win"
      ignore_errors: true

    - name: "MAIN | DeConfiguring VMs"
      include_role:
        name: configuration
      vars:
        # Common Parameters #
        vm_ip: "{{ inventory_item.vm_ip }}"
        vm_dns_domain: "{{ inventory_item.vm_dns_domain | default(default_vm_dns_domain) }}"
        
        vm_name: "{{ inventory_item.vm_name }}"
        vm_template: "{{ inventory_item.vm_template }}"
        
        datacenter: "{{ inventory_item.datacenter | default(default_datacenter) }}"
        cluster: "{{ inventory_item.cluster | default(default_cluster) }}"
        resource_pool: "{{ inventory_item.resource_pool | default(default_resource_pool) }}"

        ad_ou: "{{ inventory_item.ad_ou | default(default_ad_ou) }}"
        local_admin_groups: "{{ inventory_item.local_admin_groups | default(default_local_admin_groups) }}"
        # End Parameters #
        os: "{{ inventory_item.os }}"
        ansible_connection: winrm
        ansible_user: "{{ vm_win_username }}"
        ansible_password: "{{ vm_win_password }}"
        ansible_winrm_server_cert_validation: ignore
        uninstall: true
      with_items:
        - "{{ inventory }}"
      loop_control:
        loop_var: inventory_item
      when: inventory_item.os == "win"
      ignore_errors: true

    - name: "MAIN | DeConfiguring VMs"
      include_role:
        name: configuration
      vars:
        # Common Parameters #
        vm_ip: "{{ inventory_item.vm_ip }}"
        vm_dns_domain: "{{ inventory_item.vm_dns_domain | default(default_vm_dns_domain) }}"
        
        vm_name: "{{ inventory_item.vm_name }}"
        vm_template: "{{ inventory_item.vm_template }}"
        
        datacenter: "{{ inventory_item.datacenter | default(default_datacenter) }}"
        cluster: "{{ inventory_item.cluster | default(default_cluster) }}"
        resource_pool: "{{ inventory_item.resource_pool | default(default_resource_pool) }}"

        ad_ou: "{{ inventory_item.ad_ou | default(default_ad_ou) }}"
        local_admin_groups: "{{ inventory_item.local_admin_groups | default(default_local_admin_groups) }}"
        # End Parameters #
        os: "{{ inventory_item.os }}"
        ansible_connection: smart
        uninstall: true
      with_items:
        - "{{ inventory }}"
      loop_control:
        loop_var: inventory_item
      when: inventory_item.os != "win"
      ignore_errors: true

    - name: "MAIN | Removing Machines"
      include_role:
        name: vm_provision
      vars:
        # Common Parameters #
        vm_ip: "{{ inventory_item.vm_ip }}"
        vm_dns_domain: "{{ inventory_item.vm_dns_domain | default(default_vm_dns_domain) }}"
        
        vm_name: "{{ inventory_item.vm_name }}"
        vm_template: "{{ inventory_item.vm_template }}"
        
        datacenter: "{{ inventory_item.datacenter | default(default_datacenter) }}"
        cluster: "{{ inventory_item.cluster | default(default_cluster) }}"
        resource_pool: "{{ inventory_item.resource_pool | default(default_resource_pool) }}"

        ad_ou: "{{ inventory_item.ad_ou | default(default_ad_ou) }}"
        local_admin_groups: "{{ inventory_item.local_admin_groups | default(default_local_admin_groups) }}"
        # End Parameters #
        os: "{{ inventory_item.os }}"
        uninstall: true
      with_items:
        - "{{ inventory }}"
      loop_control:
        loop_var: inventory_item
      ignore_errors: true

