---
- name: "OS_CONFIG | Add Motd"
  template:
    src: motd.j2
    dest: /etc/motd
  
- name: "OS_CONFIG | Preparing The DISK "
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Crteating volumes"
  lvol:
    vg: data
    lv: "{{ item.vol }}"
    size: "{{ item.size }}"
  with_items: "{{ data_partitions }}"
  ignore_errors: true
  
- name: "OS_CONFIG | Crteating ext4"
  filesystem:
    dev: "/dev/data/{{ item.vol }}"
    fstype: ext4
  with_items: "{{ data_partitions }}"
    
- name: "OS_CONFIG | Mounting ext4"
  mount:
    path: "{{ item.mount }}"
    src: "/dev/data/{{ item.vol }}"
    state: mounted
    fstype: ext4
    passno: 2
  with_items:  "{{ data_partitions }}"
  