---

- include_vars: roles/configuration/defaults/admin_users.yml
- include_vars: roles/configuration/defaults/cli_users.yml
- include_vars: roles/configuration/defaults/system_groups.yml
- include_vars: roles/configuration/defaults/service_accounts.yml

- name: "OS_CONFIG | Add Motd"
  template:
    src: motd.j2
    dest: /etc/motd
  
- name: "OS_CONFIG | Preparing The DISK "
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Crteating volumes"
  lvol:
    vg: data
    lv: "{{ item.vol }}"
    size: "{{ item.size }}"
  with_items: "{{ data_partitions }}"
  ignore_errors: true
  
- name: "OS_CONFIG | Crteating ext4"
  filesystem:
    dev: "/dev/data/{{ item.vol }}"
    fstype: ext4
  with_items: "{{ data_partitions }}"
    
- name: "OS_CONFIG | Mounting ext4"
  mount:
    path: "{{ item.mount }}"
    src: "/dev/data/{{ item.vol }}"
    state: mounted
    fstype: ext4
    passno: 2
  with_items:  "{{ data_partitions }}"

- name: "OS_CONFIG | Create Groups"
  group:
    name: "{{ item.groupname }}"
    state: present
  with_items: "{{ system_groups }}"

- name: OS_CONFIG | Create Service Accounts
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
  with_items: "{{ service_accounts }}"

- name: OS_CONFIG | Create Admin Accounts
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
  with_items: "{{ admin_users }}"

- name: OS_CONFIG | Cteate User Acounts
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment }}"
  with_items: "{{ cli_users }}"

- name: OS_CONFIG | Set Passwords to Expire
  command: '/usr/bin/chage -d 0 "{{ item.name }}"'
  with_items: "{{ cli_users }}"

- name: OS_CONFIG | Add all public keys to authorized_keys
  authorized_key:
    user: "{{ item | basename | regex_replace('\-id_rsa\.pub','') }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/ssh_keys/*.pub"

- name: OS_CONFIG | Bootstrap Cfengine
  command: /var/cfengine/bin/cf-agent --bootstrap {{cf_engine_server_ip}}




  
