---
- name: "OS_CONFIG | Add Motd"
  template:
    src: motd.j2
    dest: /etc/motd
  
- name: "OS_CONFIG | Add Motd"
  template:
    src: motd.j2
    dest: /etc/issue.net
  
- name: "OS_CONFIG | Preparing The DISK "
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Creating Volume Group"
  lvg:
    vg: data
    pvs: /dev/sdb1
    pesize: 32
  
- name: "OS_CONFIG | Crteating volumes"
  lvol:
    vg: data
    lv: "{{ item.vol }}"
    size: "{{ item.size }}"
  with_items: "{{ data_partitions }}"
  ignore_errors: true
  
- name: "OS_CONFIG | Crteating xFS"
  filesystem:
    dev: "{{ item }}"
    fstype: xfs
  with_items:
    - /dev/data/current
    - /dev/data/backup
  
- name: "OS_CONFIG | Mounting FS"
  mount:
    path: "{{ item.path }}"
    src: "{{ item. src }}"
    state: mounted
    fstype: xfs
    passno: 2
  with_items:
    - { path: /data, src: /dev/data/current }
    - { path: /backup, src: /dev/data/backup }
  