---
- name: "OS_CONFIG | Configuring AD membership "
  win_domain_membership:
    dns_domain_name: "{{ ad_domain }}"
    domain_ou_path: "{{ ad_ou }}"
    hostname: "{{ vm_name }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    state: domain
  register: domain_state
  when: not uninstall

- name: "OS_CONFIG | Adding AD Group"
  win_group_membership:
    name: Administrators
    members:
      - "{{ local_admin_groups }}"
    state: present
  when: not uninstall

- name: "OS_CONFIG | Removing AD Group"
  win_group_membership:
    name: Administrators
    members:
      - "{{ local_admin_groups }}"
    state: absent
  when: uninstall
  ignore_errors: true

- name: "OS_CONFIG | Removing AD membership "
  win_domain_membership:
    dns_domain_name: "{{ ad_domain }}"
    domain_ou_path: "{{ ad_ou }}"
    hostname: "{{ vm_name }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    workgroup_name: WORKGROUP
    state: workgroup
  register: domain_state
  when: uninstall
  ignore_errors: true
