---
- name: "OS_CONFIG | Configuring AD Group "
  win_domain_membership:
    dns_domain_name: "{{ ad_domain }}"
    domain_ou_path: "{{ ad_ou }}"
    hostname: "{{ vm_name }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    state: domain
  register: domain_state

- name: "OS_CONFIG | Adding AD Group"
  win_group_membership:
    name: Administrators
    members:
      - "{{ local_admin_groups }}"
    state: present
