---
- name: Dump all vars
  template: 
    src: templates/dumpall.j2 
    dest: /tmp/ansible.all

- include_tasks: "vm_create.yml"
  when: not uninstall

- include_tasks: "vm_delete.yml"
  when: uninstall
