---
- name: "PROVISION | Create VM from template"
  vmware_guest:      
    validate_certs: false
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    resource_pool: "{{ resource_pool }}"
    name: "{{ vm_name }}"
    #folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"
    state: poweredon
    #esxi_hostname: "{{ esxi_host }}"
    hardware:
      num_cpus: "{{ cpu }}"
      memory_mb: "{{ mem_mb }}"
    disk:
      - size_gb: "{{ primary_disk }}"
        type: thin
        datastore: "{{ primary_datastore }}"

      - size_gb: "{{ data_disk }}"
        type: thin
        datastore: "{{ data_datastore }}"
    networks:
      - name: "{{ vm_network_port_group }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
        domain: "{{ vm_dns_domain }}"
        dns_servers:
        - "{{ vm_dns_server1 }}"
        - "{{ vm_dns_server2 }}"
    customization:
      autologon: yes
      domain:  "{{ vm_dns_domain }}"
      password: "{{ vm_new_password }}"
      hostname: "{{ vm_hostname }}"
      domainadmin: "{{ ad_domain_username }}"
      domainadminpassword: "{{ ad_domain_password }}"
      joindomain: "{{ ad_domain }}"
      timezone: "{{ vm_time_zone }}"
      dns_servers:
        - "{{ vm_dns_server1 }}"
        - "{{ vm_dns_server2 }}"
      #runonce:
      #- powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  register: new_vm

